spring.application.name=demo

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/entrepot
spring.datasource.username=postgres
spring.datasource.password=psql
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Facultatif
spring.jpa.open-in-view=false