spring.datasource.url=jdbc:postgresql://localhost:5432/entrepot
spring.datasource.username=postgres
spring.datasource.password=hatif
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optionnel : Permet à Hibernate de créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
