spring.application.name=demo
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/entrepot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : Affiche les requêtes SQL dans le terminal (très pratique pour le dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optionnel : Permet à Hibernate de créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
